### ISSUE TITLE
New Check: Attributes should not have `Optional: false` or `Required: false`

### ISSUE THREAD

**Issue by mbfrahry** [bflad/tfproviderlint#16]
While nothing will break if `Optional: false` or `Required: false` is specified but it is unneeded when declaring attributes. 

```
 "attribute": {
    ...
    Optional: true,
    Required: false,
}
```

to 

```
 "attribute": {
    ...
    Optional: true,
}
```

**Comment by bflad** [comment]
@mbfrahry do you think we should extend this to include `Computed: false` as well? I could go either which way on whether it should be bundled with this check or a separate one. 😄
