### ISSUE TITLE
New Check: acctest.RandStringFromCharSet(x, acctest.CharSetAlpha) is redundant

### ISSUE THREAD

**Issue by gdavison** [bflad/tfproviderlint#175]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Calling `acctest.RandStringFromCharSet(x, acctest.CharSetAlphaNum)` is redundant, since there is a function `acctest.RandString(x)` which defaults to `acctest.CharSetAlphaNum`.

### New or Affected Checks(s)

* AT###

### Flagged Provider Code

```go
rString := acctest.RandStringFromCharSet(8, acctest.CharSetAlphaNum)
```

### Passing Provider Code

```go
rString := acctest.RandString(8)
```

```go
rString := acctest.RandString(8, acctest.CharSetAlpha)
```

**Comment by bflad** [comment]
New `AT009` check will be available in version 0.20.0 of tfproviderlint, shipping in a few minutes.
