### ISSUE TITLE
tfproviderlint panics on interface conversion

### ISSUE THREAD

**Issue by remyleone** [bflad/tfproviderlint#205]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### tfproviderlint and terraform-plugin-sdk Version

```console
$ tfproviderlint -version
tfproviderlint v0.18.0

$ go mod graph | cut -d' ' -f 1 | grep terraform-plugin-sdk | uniq
github.com/hashicorp/terraform-plugin-sdk@v1.0.0
```

### Expected Behavior

I expect tfproviderlint to give me useful tips.

### Actual Behavior

```
$ tfproviderlint ./...
panic: interface conversion: types.Object is *types.Var, not *types.PkgName

goroutine 4479 [running]:
github.com/bflad/tfproviderlint/helper/astutils.IsModulePackageFunc(0x1450300, 0xc001a73d00, 0xc001a76a50, 0x13d5f63, 0x29, 0x13cb8b0, 0x11, 0x13c7ded, 0x7, 0x203000)
	/home/runner/work/tfproviderlint/tfproviderlint/helper/astutils/package.go:41 +0x2bd
github.com/bflad/tfproviderlint/helper/terraformtype/helper/validation.IsFunc(0x1450300, 0xc001a73d00, 0xc001a76a50, 0x13c7ded, 0x7, 0x100000000000)
	/home/runner/work/tfproviderlint/tfproviderlint/helper/terraformtype/helper/validation/package.go:21 +0x84
github.com/bflad/tfproviderlint/helper/analysisutils.SelectorExprRunner.func1.1(0x144bb00, 0xc001a73d00)
	/home/runner/work/tfproviderlint/tfproviderlint/helper/analysisutils/runners.go:470 +0x7c
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc001e94f00, 0xc002f51af0, 0x1, 0x1, 0xc002f51b18)
	/home/runner/work/tfproviderlint/tfproviderlint/vendor/golang.org/x/tools/go/ast/inspector/inspector.go:77 +0x9f
github.com/bflad/tfproviderlint/helper/analysisutils.SelectorExprRunner.func1(0xc00308a900, 0xc00308a900, 0x0, 0x0, 0x0)
	/home/runner/work/tfproviderlint/tfproviderlint/helper/analysisutils/runners.go:467 +0x149
golang.org/x/tools/go/analysis/internal/checker.(*action).execOnce(0xc001e68460)
	/home/runner/work/tfproviderlint/tfproviderlint/vendor/golang.org/x/tools/go/analysis/internal/checker/checker.go:690 +0x83a
sync.(*Once).doSlow(0xc001e68460, 0xc0004f1790)
	/opt/hostedtoolcache/go/1.14.7/x64/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/opt/hostedtoolcache/go/1.14.7/x64/src/sync/once.go:57
golang.org/x/tools/go/analysis/internal/checker.(*action).exec(0xc001e68460)
	/home/runner/work/tfproviderlint/tfproviderlint/vendor/golang.org/x/tools/go/analysis/internal/checker/checker.go:579 +0x60
golang.org/x/tools/go/analysis/internal/checker.execAll.func1(0xc001e68460)
	/home/runner/work/tfproviderlint/tfproviderlint/vendor/golang.org/x/tools/go/analysis/internal/checker/checker.go:567 +0x34
created by golang.org/x/tools/go/analysis/internal/checker.execAll
	/home/runner/work/tfproviderlint/tfproviderlint/vendor/golang.org/x/tools/go/analysis/internal/checker/checker.go:573 +0x119

```

**Comment by bflad** [comment]
Hi @remyleone 👋 Thank you for reporting this issue and sorry you ran into trouble here. There's certainly something wrong with the linter and it should certainly not throw an uncaught error.

While the code fix for this should be fairly straightforward to prevent the crash, it would be great to understand how it occurred. Is the Terraform Provider code being analyzed public by chance? If not, is it not a big deal, but it would be great to write some testing for this scenario. Thanks!

**Comment by bflad** [comment]
The code fix for this has been merged and will release with tfproviderlint version 0.19.0, in the next day or two.

**Comment by remyleone** [comment]
Hello, @bflad You can find the code of the provider I use here: https://github.com/scaleway/terraform-provider-scaleway/ 

Let me know if I can implement some best practices that would avoid this kind of behavior to happen.

**Comment by bflad** [comment]
Great, thank you so much. I'll take a peek through there to see if there is anything very unexpected. Hopefully you should be able to run version 0.19.0 of tfproviderlint, which was released earlier today, without this error. 👍
