### ISSUE TITLE
Homebrew Tap Warning

### ISSUE THREAD

**Issue by adarobin** [bflad/tfproviderlint#246]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### tfproviderlint and terraform-plugin-sdk Version

n/a

### Affected Check(s) or Function(s)

n/a

### Expected Behavior

Homebrew runs without warnings.

### Actual Behavior

```console
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the bflad/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/bflad/homebrew-tap/Formula/tfproviderlint.rb:9

```

### References

* https://github.com/Homebrew/brew/pull/11239
* https://stackoverflow.com/questions/45132704/what-does-bottle-unneeded-do

**Comment by bflad** [comment]
Thank you for reporting this, @adarobin 👍 Should be fixed with https://github.com/bflad/homebrew-tap/pull/1. Please reach out if that is not the case.
