### ISSUE TITLE
Support for multiline comments

### ISSUE THREAD

**Issue by mbfrahry** [bflad/tfproviderlint#248]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At the moment, lintignore doesn't work when there are multiple comments. For example,

```
// fake comment
//lintignore:S016,S023
```

the `lintignore` is ignored and the linting continues where we don't want it. 

Thank you!

**Comment by bflad** [comment]
If I had to adventure a quick guess at this, I think we need to update the comment ignore pass to split comment groups by reading each comment (or split the text on newlines) before checking for the `//lintignore` prefix.

**Comment by bflad** [comment]
This has been released in v0.28.0 👍
