### ISSUE TITLE
v0.28.0 "// lintignore" regression

### ISSUE THREAD

**Issue by armsnyder** [bflad/tfproviderlint#251]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### tfproviderlint Version

```console
$ tfproviderlint -version
v0.28.0
```

### Affected Check(s) or Function(s)

Affects the lintignore comment pass.

### Expected Behavior

Expected existing `// lintignore: XXXXX // my description` comments (with a leading space and description) to function correctly and ignore issues on the subsequent lint after upgrading from v0.27.1 to v0.28.0

### Actual Behavior

`// lintignore: XXXXX // my description` comments no longer suppress issues.

**Comment by armsnyder** [comment]
I can take a look at this.

**Comment by bflad** [comment]
For what its worth, Go comment directives should _not_ contain the space by convention: https://github.com/golang/go/issues/43776

However since the previous comment ignore logic was automatically stripping the spaces prior to v0.28.0, I guess we should still support the syntax.

**Comment by armsnyder** [comment]
Thanks for the context re: directives 👍

**Comment by bflad** [comment]
v0.28.1 has been released
