### ISSUE TITLE
Wrong apache thrift url

### ISSUE THREAD

**Issue by snivas** [bflad/tfproviderlint#30]
Currently the thrift url in go.sum is _git.apache.org/thrift.git_ which is not reachable, should it be changed to github.com/apache/thrift ?

**Comment by bflad** [comment]
Hi @snivas 👋 Thanks for reporting this and sorry for the trouble. Coinciding with the release of the [standalone Terraform Plugin SDK](https://www.terraform.io/docs/extend/plugin-sdk.html), the updated dependencies of this project no longer include `git.apache.org`. This will release with version 0.5.0 of tfproviderlint, very shortly. 👍 

Please note that 0.5.0 now requires the new `github.com/hashicorp/terraform-plugin-sdk` import paths in the provider code for the linters to correctly work. Provider code migration to the Terraform Plugin SDK is relatively straightforward though using the `tf-sdk-migrator` tool available in the link above, which checks for the few potential gotchas and can automatically do all the code updates. 😄
